update GHA cmds, `ctbk.ymrgtb_cd` fix

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,35 +30,35 @@ jobs:
     uses: ./.github/workflows/step.yml
     with:
       name: Compute station name histograms
-      run: ctbk --s3 station-meta-hist -gin create --dask
+      run: ctbk --s3 station-meta-hist create --dask -gin
     secrets: inherit
   meta_hist-latlngs:
     needs: normalized
     uses: ./.github/workflows/step.yml
     with:
       name: Compute station lat/lng histograms
-      run: ctbk --s3 station-meta-hist -gil create --dask
+      run: ctbk --s3 station-meta-hist create --dask -gil
     secrets: inherit
   group_counts-start:
     needs: normalized
     uses: ./.github/workflows/step.yml
     with:
       name: Aggregate counts by start station
-      run: ctbk --s3 aggregated -gs -ac create --dask
+      run: ctbk --s3 aggregated create --dask -gs -ac
     secrets: inherit
   group_counts-year-month-region-gender-type-bike-counts-durations:
     needs: normalized
     uses: ./.github/workflows/step.yml
     with:
       name: Aggregate counts by (month, region, gender, user type, rideable type)
-      run: ctbk --s3 aggregated -gymrgtb -acd create --dask
+      run: ctbk --s3 aggregated  create --dask -gymrgtb -acd
     secrets: inherit
   group_counts-start-end:
     needs: normalized
     uses: ./.github/workflows/step.yml
     with:
       name: Aggregate counts by station-pair
-      run: ctbk --s3 aggregated -gse -ac create --dask
+      run: ctbk --s3 aggregated create --dask -gse -ac
     secrets: inherit
   modes:
     needs: [meta_hist-names, meta_hist-latlngs, group_counts-start]
@@ -92,7 +92,11 @@ jobs:
       - run: python -m ctbk.ymrgtb_cd -f
       - name: Update www/public/assets/last_month.json
         run: |
-          last_month="$(ctbk --s3 aggregated -gymrgtb -acd urls | tail -n1 | grep -Eo '[0-9]+' | tail -n1)"
+          last_month="$(ctbk --s3 aggregated urls -gymrgtb -acd | tail -n1 | grep -Eo '[0-9]+' | tail -n1)"
+          if [ -z "$last_month" ]; then
+            echo "Failed to find last month"
+            exit 1
+          fi
           echo "Last month: $last_month"
           path=www/public/assets/last-month.json
           echo "$(jq ". = \"$last_month\"" $path)" > $path
